-- Backend Forge Seed Data - Teardown Articles
-- 3 architecture teardown articles
-- Run: psql -f supabase/seed-teardowns.sql

INSERT INTO public.teardowns (id, company, logo_color, title, read_time, summary, key_insights, architecture_overview, rfc_code_snippet, tags) VALUES
('teardown-stripe', 'Stripe', '#635bff', 'Stripe''s Payment Infrastructure: A Masterclass in Distributed Transactions', '12 min read', 'How Stripe processes billions in payments with zero data loss using a custom distributed transaction engine.', '["Stripe uses a custom saga orchestrator for payment intent lifecycle management","All payment state changes are event-sourced for perfect audit trails","Idempotency keys prevent duplicate charges across all API endpoints","Stripe''s failure modes are designed to be safe - never double-charge"]', 'Stripe''s payment infrastructure is built on three pillars: idempotency, event sourcing, and saga-based distributed transactions. Every API call accepts an idempotency key, which Stripe stores with the response for 24 hours. If a duplicate request arrives, Stripe returns the cached response without re-processing the payment.', 'class PaymentIntent(BaseModel):\n    id: str = Field(default_factory=lambda: f"pi_{secrets.token_urlsafe(24)}")\n    amount: int\n    currency: str\n    status: Literal["requires_payment_method", "requires_confirmation", "processing", "succeeded", "failed"]\n    idempotency_key: str | None = None\n\n    async def confirm(self, payment_method: str):\n        if self.status != "requires_confirmation":\n            raise PaymentError(f"Cannot confirm in status {self.status}")\n        await self._emit_event("payment_intent.confirmed", {\n            "payment_method": payment_method,\n            "idempotency_key": self.idempotency_key\n        })', '["distributed-transactions", "event-sourcing", "saga-pattern", "idempotency", "payments"]'),
('teardown-vercel', 'Vercel', '#000000', 'Vercel''s Edge Network: How Serverless Functions Scale to Billions of Requests', '14 min read', 'Inside Vercel''s edge runtime, cold start optimization, and how they achieve sub-50ms function startup globally.', '["Vercel pre-warms function instances using predictive ML models","Edge functions run in 30+ regions with automatic routing","ISR reduces function invocations by 90%","Serverless does not mean stateless - Vercel uses edge-compatible state stores"]', 'Vercel''s edge network processes billions of requests monthly across 30+ regions. The architecture separates the control plane from the data plane. When a request arrives, it is routed to the nearest edge node using anycast DNS.', 'export const config = { runtime: "edge" };\n\nexport default async function handler(req: Request) {\n  const url = new URL(req.url);\n  const region = req.headers.get("x-vercel-edge-region") || "auto";\n  const session = await kv.get(`session:${url.pathname}`);\n  const encoder = new TextEncoder();\n  const stream = new ReadableStream({\n    async start(controller) {\n      const data = await fetchFromOrigin(url.pathname);\n      controller.enqueue(encoder.encode(JSON.stringify(data)));\n      controller.close();\n    },\n  });\n  return new Response(stream, { headers: { "Content-Type": "application/json" } });\n}', '["edge-computing", "serverless", "cold-starts", "isr", "cdn"]'),
('teardown-cloudflare', 'Cloudflare', '#f38020', 'Cloudflare Workers: The Runtime That Runs at the Edge of Every Network', '11 min read', 'How Cloudflare built a serverless platform on V8 isolates that deploys to 300+ cities with zero cold starts.', '["V8 isolates provide 10x faster startup than containers","Workers KV is eventually consistent but globally distributed","Durable Objects provide strongly consistent state at the edge","Cloudflare processes 40 million HTTP requests per second"]', 'Cloudflare Workers fundamentally reimagined serverless computing by abandoning containers in favor of V8 isolates. While traditional serverless functions spin up a lightweight container (taking 250ms-3s), Workers isolates startup in under 5ms because they share the V8 engine already running on Cloudflare''s edge servers.', 'export class RateLimiter {\n  constructor(state, env) {\n    this.state = state;\n    this.durableObject = state.blockConcurrency(async () => {\n      const stored = await this.state.storage.get("count");\n      this.count = stored || 0;\n    });\n  }\n\n  async fetch(request) {\n    const ip = request.headers.get("CF-Connecting-IP");\n    const key = `rate:${ip}:${Date.now() / 60000 | 0}`;\n    const count = await this.state.storage.get(key) || 0;\n    if (count >= 100) {\n      return new Response("Rate limited", { status: 429 });\n    }\n    await this.state.storage.put(key, count + 1, { expirationTtl: 120 });\n    return new Response("OK");\n  }\n}', '["edge-computing", "v8-isolates", "durable-objects", "kv-store", "cdn"]'),
-- END_OF_INSERT
