-- Backend Forge Seed Data - 16 Tracks (4 Tiers)
-- Run: supabase db reset (or psql -f supabase/seed.sql)

-- ============================================================================
-- COURSE TRACKS (16 tracks across 4 tiers)
-- ============================================================================
-- Tier 1: Fundamentals (take in order)
-- Tier 2: Paradigm Stacks (pick your language)
-- Tier 3: Architecture & Patterns (apply across stacks)
-- Tier 4: Specialization (deep expertise)
-- ============================================================================

INSERT INTO public.course_tracks (id, track_number, title, tagline, paradigm, badge_color, icon_name, description, learning_goals, deliverable, is_published) VALUES

-- ============================================================================
-- TIER 1: FUNDAMENTALS
-- ============================================================================
('track-1-api-blueprint', 1, 'The API Blueprint', 'REST, OpenAPI, GraphQL & API Design', 'API Design', 'border-sky-500/40 text-sky-400 bg-sky-500/10', 'Globe', 'Master API design with REST conventions, OpenAPI specifications, GraphQL schemas, versioning strategies, rate limiting, and contract-first development.', '["Design RESTful APIs following Richardson Maturity Model","Generate OpenAPI 3.1 specs from code","Implement GraphQL resolvers with DataLoader N+1 prevention","Build API versioning strategies (URL, header, content-type)"]'::jsonb, '{"title":"Production API Gateway with Rate Limiting","description":"A complete API layer with versioning, rate limiting, OpenAPI docs, and GraphQL federation.","techStack":["TypeScript","Express","GraphQL","OpenAPI","Redis","Zod"]}'::jsonb, true),

('track-2-node-ts', 2, 'The Ubiquitous Backend', 'Node.js, TypeScript & Production Scale Architecture', 'Node.js & TypeScript', 'border-emerald-500/40 text-emerald-400 bg-emerald-500/10', 'Server', 'Master advanced TypeScript, non-blocking I/O event loops, database transaction boundaries with Drizzle/Postgres, gRPC vs REST, and resilient webhook queues.', '["Understand Node.js Event Loop phases","Design idempotent webhook ingestion with Redis SETNX locks","Optimize Postgres connection pooling and row-level locks","Build multi-tenant SaaS billing engines"]'::jsonb, '{"title":"Multi-Tenant Idempotent SaaS Webhook Engine","description":"A production-grade webhook ingestion service capable of processing 25,000 req/sec.","techStack":["Fastify","TypeScript","PostgreSQL","Drizzle ORM","Redis","BullMQ"]}'::jsonb, true),

('track-3-database-mastery', 3, 'Database Mastery', 'PostgreSQL Internals, Indexing & Query Optimization', 'Database Engineering', 'border-blue-500/40 text-blue-400 bg-blue-500/10', 'Database', 'Master PostgreSQL internals including B-tree indexes, query planner analysis, connection pooling with PgBouncer, migration strategies, and performance profiling.', '["Analyze query execution plans with EXPLAIN ANALYZE","Design composite indexes for complex WHERE clauses","Configure PgBouncer connection pooling for 10k+ connections","Implement zero-downtime migration strategies"]'::jsonb, '{"title":"High-Performance Database Layer","description":"An optimized PostgreSQL setup with connection pooling, read replicas, and automated migration pipeline.","techStack":["PostgreSQL","PgBouncer","Drizzle ORM","Node.js","Redis"]}'::jsonb, true),

('track-4-auth-security', 4, 'Auth & Security', 'OAuth2, JWT, RBAC & Application Security', 'Security Engineering', 'border-red-500/40 text-red-400 bg-red-500/10', 'ShieldCheck', 'Master authentication and authorization with OAuth2 flows, JWT token management, RBAC/ABAC models, API key rotation, CORS policies, and OWASP Top 10 defenses.', '["Implement OAuth2 Authorization Code flow with PKCE","Design JWT access + refresh token rotation","Build RBAC and ABAC authorization models","Defend against OWASP Top 10 vulnerabilities"]'::jsonb, '{"title":"Enterprise Auth Service","description":"A production authentication service with OAuth2, MFA, session management, and audit logging.","techStack":["TypeScript","PostgreSQL","Redis"," bcrypt","OTEL"]}'::jsonb, true),

-- ============================================================================
-- TIER 2: PARADIGM STACKS
-- ============================================================================
('track-5-python-backend', 5, 'The Python Backend', 'FastAPI, Async Python & Data Pipelines', 'Python & FastAPI', 'border-yellow-500/40 text-yellow-400 bg-yellow-500/10', 'Server', 'Build production Python backends with FastAPI async endpoints, SQLAlchemy ORM, Pydantic validation, Celery task queues, and Python type safety patterns.', '["Build async FastAPI endpoints with dependency injection","Implement SQLAlchemy 2.0 async ORM with relationship loading","Design Pydantic v2 models for strict validation","Configure Celery workers with Redis broker and retry policies"]'::jsonb, '{"title":"Async Python SaaS API","description":"A production FastAPI backend with async database access, background tasks, and OpenAPI auto-docs.","techStack":["Python","FastAPI","SQLAlchemy 2.0","Pydantic v2","Celery","Redis"]}'::jsonb, true),

('track-6-rails', 6, 'The Rails Monolith Engine', 'Ruby on Rails 7+, Hotwire & Modular Architecture', 'Ruby on Rails 7+', 'border-rose-500/40 text-rose-400 bg-rose-500/10', 'Server', 'Master Rails 7.2 modular monoliths, Hotwire real-time streams, Sidekiq background jobs, and multi-tenant database sharding.', '["Build modular Rails engines with Packwerk","Implement Hotwire Turbo Streams","Design Sidekiq worker pools","Master ActiveRecord transaction isolation"]'::jsonb, '{"title":"Production SaaS Billing Engine with Hotwire","description":"A modular Rails monolith with real-time billing updates and Stripe integration.","techStack":["Ruby on Rails 7.2","Hotwire","Sidekiq","PostgreSQL","Redis","Stripe"]}'::jsonb, true),

('track-7-go-service', 7, 'The Go Service', 'Go Microservices, gRPC & Concurrency', 'Go', 'border-cyan-500/40 text-cyan-400 bg-cyan-500/10', 'Server', 'Build production Go microservices with gRPC gateways, channel-based concurrency, graceful shutdown, structured logging, and Go-specific performance patterns.', '["Build gRPC service gateways with Go","Design channel-based worker pools with backpressure","Implement graceful shutdown with context propagation","Use sync.Pool and arena allocators for zero-GC hot paths"]'::jsonb, '{"title":"Go Microservice Gateway","description":"A high-performance Go microservice with gRPC, structured logging, and health checks.","techStack":["Go","gRPC","Protocol Buffers","Zap","Prometheus"]}'::jsonb, true),

('track-8-enterprise-java', 8, 'The Enterprise Java', 'Spring Boot, JPA & Enterprise Patterns', 'Java & Spring Boot', 'border-orange-500/40 text-orange-400 bg-orange-500/10', 'Server', 'Build enterprise Java applications with Spring Boot, Spring Security, JPA/Hibernate, transaction management, and microservice patterns.', '["Build REST APIs with Spring Boot and dependency injection","Implement JPA entities with lazy loading and query optimization","Configure Spring Security with OAuth2 resource server","Design transactional outbox with Spring Transaction Synchronization"]'::jsonb, '{"title":"Spring Boot Microservice","description":"A production Spring Boot service with security, caching, and distributed tracing.","techStack":["Java","Spring Boot 3","Spring Security","JPA","Maven","Docker"]}'::jsonb, true),

-- ============================================================================
-- TIER 3: ARCHITECTURE & PATTERNS
-- ============================================================================
('track-9-infra-code', 9, 'The Infrastructure Engineer', 'Terraform, Kubernetes & Infrastructure as Code', 'Infrastructure as Code', 'border-amber-500/40 text-amber-400 bg-amber-500/10', 'Layers', 'Master infrastructure as code with Terraform module composition, Kubernetes custom operators, remote state management, and declarative infrastructure.', '["Build reusable Terraform modules with remote state management","Implement Kubernetes custom operators with CRDs and reconciliation loops","Design multi-environment infrastructure with Terragrunt","Configure infrastructure monitoring and drift detection"]'::jsonb, '{"title":"Multi-Region Kubernetes Deployment","description":"A production infrastructure stack with Terraform modules, K8s operators, and GitOps.","techStack":["Terraform","Kubernetes","Helm","Terragrunt","Go"]}'::jsonb, true),

('track-10-observability', 10, 'The Observability Engineer', 'Metrics, Tracing, Logging & SRE Practices', 'Observability & SRE', 'border-teal-500/40 text-teal-400 bg-teal-500/10', 'Activity', 'Master the three pillars of observability: structured logging with correlation IDs, distributed tracing with OpenTelemetry, and metric dashboards with Prometheus/Grafana.', '["Implement structured logging with trace context propagation","Build distributed traces across microservices with OpenTelemetry","Design Prometheus metrics with RED method (Rate, Errors, Duration)","Create Grafana dashboards for SLO monitoring and error budgets"]'::jsonb, '{"title":"Observability Stack","description":"A complete observability layer with logs, metrics, traces, and alerting.","techStack":["OpenTelemetry","Prometheus","Grafana","Loki","TypeScript"]}'::jsonb, true),

('track-11-api-gateway', 11, 'The API Gateway Architect', 'Kong, Envoy & Gateway Patterns', 'API Gateway Patterns', 'border-violet-500/40 text-violet-400 bg-violet-500/10', 'Zap', 'Master API gateway patterns with Kong plugin development, Envoy WASM filters, rate limiting, authentication, and traffic management.', '["Build Kong Gateway plugins for rate limiting and authentication","Implement Envoy WASM filters for edge security","Design traffic splitting and canary routing","Configure circuit breakers and connection pooling"]'::jsonb, '{"title":"Production API Gateway with Rate Limiting","description":"A multi-layer API gateway with Kong, Envoy, and custom WASM plugins.","techStack":["Kong","Envoy","Lua","Go","Redis"]}'::jsonb, true),

('track-12-cicd', 12, 'The CI/CD Pipeline Engineer', 'GitHub Actions, ArgoCD & GitOps', 'CI/CD Pipelines', 'border-purple-500/40 text-purple-400 bg-purple-500/10', 'Bot', 'Master CI/CD pipelines with GitHub Actions matrix builds, ArgoCD GitOps deployments, canary rollouts, and progressive delivery.', '["Design GitHub Actions workflows with matrix builds and reusable workflows","Implement ArgoCD GitOps deployments with ApplicationSets","Build canary deployments with Argo Rollouts","Configure progressive delivery and rollback strategies"]'::jsonb, '{"title":"GitOps Deployment Pipeline","description":"A complete CI/CD pipeline with GitHub Actions, ArgoCD, and canary deployments.","techStack":["GitHub Actions","ArgoCD","Kubernetes","Helm","Argo Rollouts"]}'::jsonb, true),

-- ============================================================================
-- TIER 4: SPECIALIZATION
-- ============================================================================
('track-13-event-sourcing', 13, 'The Event Sourcing Architect', 'EventStoreDB, CQRS & Distributed Sagas', 'Event Sourcing & CQRS', 'border-orange-500/40 text-orange-400 bg-orange-500/10', 'Server', 'Master event sourcing with EventStoreDB, catch-up projections, CQRS read/write separation, and distributed saga orchestration with compensation.', '["Build event-sourced aggregates with EventStoreDB","Implement catch-up projections for read models","Design distributed sagas with compensation handlers","Handle event versioning and schema evolution"]'::jsonb, '{"title":"Distributed Saga Orchestrator","description":"An event-sourced system with CQRS projections and saga-based distributed transactions.","techStack":["TypeScript","EventStoreDB","Node.js","Redis"]}'::jsonb, true),

('track-14-service-mesh', 14, 'The Service Mesh Engineer', 'Istio, Consul & Zero-Trust Networking', 'Service Mesh', 'border-emerald-500/40 text-emerald-400 bg-emerald-500/10', 'ShieldCheck', 'Master service mesh patterns with Istio traffic management, Consul intentions, mutual TLS, circuit breaking, and zero-trust networking.', '["Configure Istio VirtualService for traffic splitting and routing","Implement Consul intentions for zero-trust service-to-service security","Enable mutual TLS across service mesh with automatic certificate rotation","Design circuit breaking and retry policies for resilient services"]'::jsonb, '{"title":"Multi-Tenant SaaS Platform","description":"A production service mesh with Istio, Consul, and zero-trust networking.","techStack":["Istio","Consul","Envoy","Kubernetes","Go"]}'::jsonb, true),

('track-15-chaos', 15, 'The Chaos Engineer', 'Litmus, Chaos Monkey & Resilience Testing', 'Chaos Engineering', 'border-indigo-500/40 text-indigo-400 bg-indigo-500/10', 'Cpu', 'Master chaos engineering with Litmus experiments, steady-state hypothesis validation, GameDay orchestration, and blast radius control.', '["Design chaos experiments with Litmus for pod and network failures","Implement steady-state hypothesis validation for resilience testing","Build GameDay orchestration for team exercises","Create blast radius control for safe production chaos"]'::jsonb, '{"title":"Chaos-Resilient Production System","description":"A chaos engineering platform with automated experiments and resilience validation.","techStack":["Litmus","Kubernetes","Prometheus","Go"]}'::jsonb, true),

('track-16-capstone', 16, 'Backend Forge Capstone', 'Full-Stack Production API & Integration', 'Final Capstone', 'border-pink-500/40 text-pink-400 bg-pink-500/10', 'Radio', 'Apply all learned skills in a capstone project: build and deploy a production API with auth, billing, observability, CI/CD, and chaos testing.', '["Apply production hardening checklist before launch","Integrate OAuth2, billing, and observability into a single API","Deploy to Kubernetes with ArgoCD and canary releases","Run chaos experiments and validate system resilience"]'::jsonb, '{"title":"Backend Forge Capstone: Full-Stack Production API","description":"The final capstone integrating all skills into a production-ready system.","techStack":["TypeScript","Express","Stripe","OpenTelemetry","Kubernetes","ArgoCD"]}'::jsonb, true);
