-- Backend Forge Seed Data - Teardown Articles (SEO-Optimized)
-- 5 architecture teardown articles with FAQ pairs for Google featured snippets
-- Run: psql -f supabase/seed-teardowns.sql

INSERT INTO public.teardowns (id, company, logo_color, title, read_time, summary, key_insights, architecture_overview, rfc_code_snippet, tags, slug, published_at, author, faq_pairs, seo_description, keywords) VALUES
('teardown-stripe', 'Stripe', '#635bff', 'Stripe''s Payment Infrastructure: A Masterclass in Distributed Transactions', '12 min read', 'How Stripe processes billions in payments with zero data loss using a custom distributed transaction engine.', '["Stripe uses a custom saga orchestrator for payment intent lifecycle management","All payment state changes are event-sourced for perfect audit trails","Idempotency keys prevent duplicate charges across all API endpoints","Stripe''s failure modes are designed to be safe - never double-charge"]', 'Stripe''s payment infrastructure is built on three pillars: idempotency, event sourcing, and saga-based distributed transactions. Every API call accepts an idempotency key, which Stripe stores with the response for 24 hours. If a duplicate request arrives, Stripe returns the cached response without re-processing the payment.', 'class PaymentIntent(BaseModel):\n    id: str = Field(default_factory=lambda: f"pi_{secrets.token_urlsafe(24)}")\n    amount: int\n    currency: str\n    status: Literal["requires_payment_method", "requires_confirmation", "processing", "succeeded", "failed"]\n    idempotency_key: str | None = None\n\n    async def confirm(self, payment_method: str):\n        if self.status != "requires_confirmation":\n            raise PaymentError(f"Cannot confirm in status {self.status}")\n        await self._emit_event("payment_intent.confirmed", {\n            "payment_method": payment_method,\n            "idempotency_key": self.idempotency_key\n        })', '["distributed-transactions", "event-sourcing", "saga-pattern", "idempotency", "payments"]', 'stripe-payment-infrastructure', '2026-03-15T00:00:00Z', 'Backend Forge Team',
'[{"question": "How does Stripe prevent duplicate charges?", "answer": "Stripe uses idempotency keys on every API call. Each request includes a unique key that Stripe stores for 24 hours. If a duplicate request arrives with the same key, Stripe returns the cached response without re-processing the payment."},{"question": "What distributed transaction pattern does Stripe use?", "answer": "Stripe uses a saga orchestrator pattern for payment intent lifecycle management. Each payment goes through a state machine: requires_payment_method → requires_confirmation → processing → succeeded/failed, with event sourcing for perfect audit trails."},{"question": "How does Stripe handle payment failures safely?", "answer": "Stripe''s failure modes are designed to be safe — they never double-charge. Failed payments trigger compensating transactions that reverse any partial state changes, ensuring exactly-once semantics across distributed systems."},{"question": "What is Stripe''s approach to API reliability?", "answer": "Every Stripe API endpoint accepts an idempotency key. The response is stored alongside the key for 24 hours. This prevents duplicate charges from network retries and ensures reliable payment processing even under high concurrency."}]',
'Learn how Stripe processes billions in payments with zero data loss using idempotency keys, event sourcing, and saga-based distributed transactions.',
'["stripe architecture", "distributed transactions", "payment processing", "idempotency", "event sourcing", "saga pattern"]'),

('teardown-vercel', 'Vercel', '#000000', 'Vercel''s Edge Network: How Serverless Functions Scale to Billions of Requests', '14 min read', 'Inside Vercel''s edge runtime, cold start optimization, and how they achieve sub-50ms function startup globally.', '["Vercel pre-warms function instances using predictive ML models","Edge functions run in 30+ regions with automatic routing","ISR reduces function invocations by 90%","Serverless does not mean stateless - Vercel uses edge-compatible state stores"]', 'Vercel''s edge network processes billions of requests monthly across 30+ regions. The architecture separates the control plane from the data plane. When a request arrives, it is routed to the nearest edge node using anycast DNS.', 'export const config = { runtime: "edge" };\n\nexport default async function handler(req: Request) {\n  const url = new URL(req.url);\n  const region = req.headers.get("x-vercel-edge-region") || "auto";\n  const session = await kv.get(`session:${url.pathname}`);\n  const encoder = new TextEncoder();\n  const stream = new ReadableStream({\n    async start(controller) {\n      const data = await fetchFromOrigin(url.pathname);\n      controller.enqueue(encoder.encode(JSON.stringify(data)));\n      controller.close();\n    },\n  });\n  return new Response(stream, { headers: { "Content-Type": "application/json" } });\n}', '["edge-computing", "serverless", "cold-starts", "isr", "cdn"]', 'vercel-edge-network', '2026-04-01T00:00:00Z', 'Backend Forge Team',
'[{"question": "How does Vercel achieve sub-50ms cold starts?", "answer": "Vercel pre-warms function instances using predictive ML models that anticipate traffic patterns. Combined with their lightweight V8 isolate runtime, functions start in under 50ms globally across 30+ edge regions."},{"question": "What is Vercel''s ISR and how does it reduce function calls?", "answer": "Incremental Static Regeneration (ISR) pre-renders pages at build time and serves them from the edge cache. This reduces function invocations by 90% because most requests are served statically without executing any server-side code."},{"question": "How does Vercel route requests to the nearest edge?", "answer": "Vercel uses anycast DNS to route incoming requests to the nearest edge node. Each request hits the closest of 30+ regions automatically, with the edge node handling caching, rendering, and function execution locally."},{"question": "Is Vercel''s edge runtime truly stateless?", "answer": "No. While serverless functions are often stateless, Vercel provides edge-compatible state stores like KV and Edge Config that maintain state at the edge with sub-millisecond reads, enabling session management and real-time features."}]',
'Discover how Vercel''s edge network scales serverless functions to billions of requests with sub-50ms cold starts, ISR caching, and 30+ global regions.',
'["vercel edge", "serverless cold starts", "edge computing", "ISR", "CDN", "vercel architecture"]'),

('teardown-cloudflare', 'Cloudflare', '#f38020', 'Cloudflare Workers: The Runtime That Runs at the Edge of Every Network', '11 min read', 'How Cloudflare built a serverless platform on V8 isolates that deploys to 300+ cities with zero cold starts.', '["V8 isolates provide 10x faster startup than containers","Workers KV is eventually consistent but globally distributed","Durable Objects provide strongly consistent state at the edge","Cloudflare processes 40 million HTTP requests per second"]', 'Cloudflare Workers fundamentally reimagined serverless computing by abandoning containers in favor of V8 isolates. While traditional serverless functions spin up a lightweight container (taking 250ms-3s), Workers isolates startup in under 5ms because they share the V8 engine already running on Cloudflare''s edge servers.', 'export class RateLimiter {\n  constructor(state, env) {\n    this.state = state;\n    this.durableObject = state.blockConcurrency(async () => {\n      const stored = await this.state.storage.get("count");\n      this.count = stored || 0;\n    });\n  }\n\n  async fetch(request) {\n    const ip = request.headers.get("CF-Connecting-IP");\n    const key = `rate:${ip}:${Date.now() / 60000 | 0}`;\n    const count = await this.state.storage.get(key) || 0;\n    if (count >= 100) {\n      return new Response("Rate limited", { status: 429 });\n    }\n    await this.state.storage.put(key, count + 1, { expirationTtl: 120 });\n    return new Response("OK");\n  }\n}', '["edge-computing", "v8-isolates", "durable-objects", "kv-store", "cdn"]', 'cloudflare-workers-runtime', '2026-04-15T00:00:00Z', 'Backend Forge Team',
'[{"question": "Why are Cloudflare Workers faster than traditional serverless?", "answer": "Cloudflare Workers use V8 isolates instead of containers. V8 isolates share the already-running V8 engine on edge servers, enabling startup in under 5ms compared to 250ms-3s for container-based serverless functions."},{"question": "What are Cloudflare Durable Objects?", "answer": "Durable Objects provide strongly consistent, single-instance state at the edge. Each Durable Object is a globally unique JavaScript class instance that handles all requests for a specific entity, enabling real-time collaboration and stateful edge computing."},{"question": "How many requests does Cloudflare process per second?", "answer": "Cloudflare processes approximately 40 million HTTP requests per second across their global network of 300+ cities. This makes Workers one of the highest-throughput serverless platforms in the world."},{"question": "Is Workers KV eventually consistent?", "answer": "Yes. Workers KV is eventually consistent — writes propagate globally within seconds. For strongly consistent state, use Durable Objects which provide single-instance consistency for any given key."}]',
'Learn how Cloudflare Workers uses V8 isolates to achieve zero cold starts across 300+ cities, processing 40 million requests per second with Durable Objects.',
'["cloudflare workers", "V8 isolates", "edge computing", "durable objects", "serverless", "cloudflare architecture"]'),

('teardown-shopify', 'Shopify', '#96bf48', 'Shopify''s Checkout: How They Process $1B in Black Friday Traffic', '16 min read', 'The architecture behind Shopify''s checkout flow handling 80,000 requests per second during peak traffic.', '["Shopify uses a monolith-to-microservices migration with the strangler fig pattern","Checkout uses a custom state machine with optimistic UI updates","They pre-warm database connections 30 minutes before traffic spikes","Redis Cluster handles session state with sub-millisecond reads"]', 'Shopify''s checkout is one of the highest-traffic e-commerce flows on the planet. During Black Friday 2024, it processed over $1B in GMV with zero downtime. The architecture evolved from a Rails monolith to a modular system where checkout is a isolated service communicating via event-driven messaging.', 'class CheckoutStateMachine:\n    def __init__(self, order_id: str):\n        self.order_id = order_id\n        self.state = "cart"\n        self.transitions = {\n            "cart": ["address", "payment"],\n            "address": ["payment", "cart"],\n            "payment": ["confirmation", "address"],\n            "confirmation": []\n        }\n\n    def transition(self, new_state: str):\n        if new_state not in self.transitions.get(self.state, []):\n            raise InvalidTransition(f"{self.state} -> {new_state}")\n        self.state = new_state\n        self._emit_event("checkout.transitioned", {\n            "order_id": self.order_id,\n            "from": self.state,\n            "to": new_state\n        })', '["e-commerce", "checkout", "state-machine", "high-traffic", "monolith-migration"]', 'shopify-checkout-scalability', '2026-05-01T00:00:00Z', 'Backend Forge Team',
'[{"question": "How does Shopify handle Black Friday traffic spikes?", "answer": "Shopify pre-warms database connections 30 minutes before anticipated traffic spikes. They use Redis Cluster for session state with sub-millisecond reads, and the checkout service communicates via event-driven messaging to handle 80,000+ requests per second."},{"question": "What migration pattern did Shopify use for checkout?", "answer": "Shopify used the strangler fig pattern to gradually extract checkout from their Rails monolith into an isolated service. This allowed them to modernize the checkout flow without disrupting the rest of the platform."},{"question": "How does Shopify''s checkout state machine work?", "answer": "Checkout uses a custom state machine with states: cart → address → payment → confirmation. Each transition emits events for audit trails and optimistic UI updates, ensuring consistent state across distributed services."},{"question": "How much revenue did Shopify process on Black Friday 2024?", "answer": "Shopify processed over $1 billion in GMV (Gross Merchandise Volume) during Black Friday 2024 with zero downtime, handling peak traffic of 80,000 requests per second across their distributed infrastructure."}]',
'Discover how Shopify''s checkout processes $1B in Black Friday traffic with 80K requests/second, using state machines, Redis Cluster, and the strangler fig pattern.',
'["shopify checkout", "high traffic architecture", "state machine", "monolith migration", "redis cluster", "e-commerce"]'),

('teardown-discord', 'Discord', '#5865F2', 'Discord''s Real-Time Infrastructure: Scaling WebSocket Connections to 500M Users', '13 min read', 'How Discord built a real-time messaging platform that handles 500 million messages per day across millions of WebSocket connections.', '["Discord uses Elixir/BEAM for connection handling - each connection is a lightweight process","Messages are stored in Cassandra for write scalability and ScyllaDB for reads","They migrated from MongoDB to Cassandra to handle write amplification","Voice channels use UDP with custom congestion control"]', 'Discord serves 500 million messages daily across hundreds of millions of WebSocket connections. Their architecture is built on Elixir/BEAM, where each connection is a lightweight process (not a thread or goroutine). This allows them to handle millions of concurrent connections with predictable memory usage.', 'defmodule Discord.Gateway.Connection do\n  use GenServer\n\n  def init(socket) do\n    {:ok, %{\n      socket: socket,\n      user_id: nil,\n      guilds: [],\n      heartbeat_ref: nil\n    }}\n  end\n\n  def handle_info({:heartbeat, interval}, state) do\n    :ok = send_heartbeat(state.socket)\n    ref = Process.send_after(self(), {:heartbeat, interval}, interval)\n    {:noreply, %{state | heartbeat_ref: ref}}\n  end\n\n  def handle_info({:gateway_dispatch, payload}, state) do\n    :ok = dispatch_to_handlers(payload, state)\n    {:noreply, state\n  end\nend', '["real-time", "websockets", "elixir", "beam", "scaling"]', 'discord-real-time-infrastructure', '2026-05-15T00:00:00Z', 'Backend Forge Team',
'[{"question": "How does Discord handle millions of WebSocket connections?", "answer": "Discord uses Elixir/BEAM where each WebSocket connection is a lightweight process (not a thread). BEAM processes use only ~2KB of memory, allowing millions of concurrent connections with predictable resource usage and fault isolation."},{"question": "Why did Discord migrate from MongoDB to Cassandra?", "answer": "Discord experienced write amplification issues with MongoDB at scale. Cassandra provided better write scalability for their message storage pattern, while ScyllaDB (a Cassandra-compatible database) handles read-heavy workloads with lower latency."},{"question": "How does Discord handle voice channels?", "answer": "Discord voice channels use UDP with custom congestion control instead of TCP. This provides lower latency for real-time audio, with their custom protocol handling packet loss, jitter buffering, and adaptive bitrate encoding."},{"question": "What is the memory footprint of a Discord connection?", "answer": "Each Discord connection on Elixir/BEAM uses approximately 2KB of memory as a lightweight process. This is orders of magnitude smaller than thread-based approaches, enabling millions of concurrent connections on a single server."}]',
'Learn how Discord scales WebSocket connections to 500M users with Elixir/BEAM processes, handles 500M daily messages, and uses Cassandra for write scalability.',
'["discord architecture", "websocket scaling", "elixir beam", "real-time messaging", "cassandra", "distributed systems"]')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  published_at = EXCLUDED.published_at,
  author = EXCLUDED.author,
  faq_pairs = EXCLUDED.faq_pairs,
  seo_description = EXCLUDED.seo_description,
  keywords = EXCLUDED.keywords;
