export const PRICING = {
  PRO_LIFETIME_PRICE: 199,
  PRO_LIFETIME_PRICE_DISPLAY: '$199',
  PRO_ORIGINAL_PRICE: 599,
  PRO_ORIGINAL_PRICE_DISPLAY: '$599',
  STRIPE_PRICE_ID: import.meta.env.VITE_STRIPE_PRICE_PRO_LIFETIME || '',
  ENROLLMENT_COUNT: '2,847',
} as const;
